# Generated by Django 3.1.5 on 2023-12-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0002_auto_20231210_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='movies',
            new_name='movie',
        ),
    ]
