# Generated by Django 3.1.5 on 2023-12-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0005_auto_20231222_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='watch_id',
            new_name='hist_id',
        ),
    ]
